# Generated by Django 4.2.7 on 2023-11-13 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("group_id", models.IntegerField(primary_key=True, serialize=False)),
                ("group_name", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["group_name"],
            },
        ),
        migrations.CreateModel(
            name="List",
            fields=[
                ("list_id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.IntegerField(primary_key=True, serialize=False)),
                ("task_name", models.CharField(max_length=200)),
                ("note", models.TextField()),
                ("file", models.FileField(upload_to="")),
                ("priority", models.IntegerField()),
                ("deadline", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("t", "To do"), ("i", "In progress"), ("d", "Done")],
                        default="t",
                        help_text="Task status",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_logged_in", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SharedList",
            fields=[
                (
                    "sharedlist_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "group_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="catalog.group"
                    ),
                ),
                (
                    "list_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="catalog.list"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                ("reminder_id", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                (
                    "task_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="catalog.task"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="catalog.user"
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="ListEntry",
            fields=[
                (
                    "listentry_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "list_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="catalog.list"
                    ),
                ),
                (
                    "task_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="catalog.task"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="list",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="catalog.user"
            ),
        ),
        migrations.CreateModel(
            name="GroupEntry",
            fields=[
                (
                    "groupentry_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "group_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="catalog.group"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="catalog.user"
                    ),
                ),
            ],
        ),
    ]
