# Generated by Django 4.2.7 on 2023-11-14 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                ("list_id", models.AutoField(primary_key=True, serialize=False)),
                ("list_name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("task_name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(blank=True, upload_to="")),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[("l", "Low"), ("m", "Medium"), ("h", "High")],
                        help_text="Task priority",
                        max_length=1,
                    ),
                ),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("t", "To do"), ("i", "In progress"), ("d", "Done")],
                        default="t",
                        help_text="Task status",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=200, unique=True)),
                ("password", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("u", "User"), ("a", "Admin"), ("s", "Super User")],
                        default="u",
                        max_length=1,
                    ),
                ),
                ("is_logged_in", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                ("reminder_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                (
                    "task_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="catalog.task",
                        to_field="task_name",
                    ),
                ),
                (
                    "user_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="catalog.user",
                        to_field="username",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="ListEntry",
            fields=[
                ("listentry_id", models.AutoField(primary_key=True, serialize=False)),
                ("assigned_tasks", models.ManyToManyField(to="catalog.task")),
                (
                    "list_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="catalog.list",
                        to_field="list_name",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="list",
            name="assigned_users",
            field=models.ManyToManyField(to="catalog.user"),
        ),
    ]
