# Generated by Django 4.2.7 on 2023-11-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("l", "Low"), ("m", "Medium"), ("h", "High")],
                help_text="Task priority",
                max_length=1,
            ),
        ),
    ]
